[build]
  command = "npm run build"
  publish = "out"  # Next.js static export directory

# Handle 404s correctly with Next.js
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Optimize for performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;" 